### ISSUE TITLE
require 'rltk/ast' pollute main Object with #match method, leaking it in a global scope

### ISSUE THREAD

**Issue by libo** [chriswailes/RLTK#37]
Hi!

First of all thanks for this tool!

I have noticed that the following line in the `ASTNode` 
```ruby
require 'filigree/match'
```
https://github.com/chriswailes/RLTK/blob/master/lib/rltk/ast.rb

Actually will include this in the main Object 
```ruby
def match(*objects, &block)
  me = Filigree::MatchEnvironment.new
  me.instance_exec &block
  me.find_match(objects)
end
```
https://github.com/chriswailes/filigree/blob/master/lib/filigree/match.rb#L157

It looks like RLTK doesn't use `#match` but only the module `Filigree::Destructurable` as described in this commit that introduced the inclusion: https://github.com/chriswailes/RLTK/commit/3cf628c07402bc43b3fd9cb6a502a9e3eabc3d12

I was wondering if we could avoid leaking the `match` method in a global scope.
I have noticed since including rltk/ast started to conflict with rspec 

Thanks!

**Comment by codella** [comment]
Well, good that this has been brought up! In particular, this is clashing with a `match` method that is supposed to be available whenever you want to define an RSpec matcher by yourself, for instance:

```ruby
require 'rspec/expectations'

RSpec::Matchers.define :be_a_multiple_of do |expected|
  match do |actual|
    actual % expected == 0
  end
end
```

**Comment by libo** [comment]
Well @codella actually I have found a workaround. 

in your node class you could do
```ruby
require 'rltk/ast'
Object.send :undef_method, :match

class BaseNode < RLTK::ASTNode
  ..
end
```

But, yes... not very elegant. It would be better if we just include `Filigree::Destructurable` and avoid defining `match` on the `Object` class

**Comment by chriswailes** [comment]
This is certainly something I can work on.  I might need your help with testing though, as I currently don't have any environment that causes this problem.

I'd appreciate it if you could also leave me a short description of how/why you are using RLTK.  This helps me understand how people are using RLTK and if it is meeting people's needs.

**Comment by chriswailes** [comment]
So, my `match` is a function and not a method of some particular object.  It looks like Ruby might implement functions by making them methods of Object, but that doesn't always seem to be the case.  Can you get your code to work by using `self.match` instead of `match`?  If that doesn't work, the only solution I see is to re-name the Filigree-provided function to something like `pmatch` (for 'pattern-match').

**Comment by libo** [comment]
Hi 
At this moment in time I can't disclose what we are working on, I am sorry. Anyway we have all the intentions to opensource the project as soon as possible.

The issue we see here is that after `require 'filigree/match' ` any constants, method or globals within the loaded source file will be available in the calling program’s global namespace.

When you do a 
```ruby
def match
  puts "foo"
end
```

you are actually defining a method in the ruby `main` object 
```
» irb
def match; puts "foo"; end

method(:match).owner
 => Object

self
 => main
```

Instead of renaming it with `pmatch` (so to introduce some sort of naming spacing "p") why don't you go for a real namespace and use a module 

```ruby
module Filigree 
  def match
    puts "foo"
  end
end
```

The function will be still available as a global `::Filigree.match`

**Comment by libo** [comment]
I can confirm that this would work

```ruby
require 'rspec/expectations'

RSpec::Matchers.define :be_a_multiple_of do |expected|
  self.match do |actual|
    actual % expected == 0
  end
end
```

The point is that rspec is loaded before Filigree and hence the latest will define a `match` method that will override the one in rspec even if they define it in a module:
https://github.com/rspec/rspec-expectations/blob/7628434b8e10620669bf34f9b341acbd7e5946ee/lib/rspec/matchers/dsl.rb#L57

In my humble opinion your match function as it is now is hitting a bit the principle of least astonishment .

Sorry for my rant :-)

**Comment by chriswailes** [comment]
This issue was fixed by moving the match function provided by Filigree into the Filigree namespace.  Please file any followup issues to the Filigree Github page.

Relevant patch: https://github.com/chriswailes/filigree/commit/ead2f44483fedd51638dc982c9e7801f1c5d6932
