### ISSUE TITLE
RLTK::LexingError carries a wrong line_offset.

### ISSUE THREAD

**Issue by codella** [chriswailes/RLTK#38]
Let's say that I have the following rule in the lexer:
```
rule(/a/)
```
and the following string (with 3 leading spaces):
```
   aaab
```
Lexing it, what I get is a RLTK::LexingError whose `line_offset` is supposed to be `6`, but I actually get a way lower number (I guess in this case it would be `3`)

Let me know if you want me to write a test that fails for this bug, in case my description is not clear enough :^)

cc: @libo

**Comment by chriswailes** [comment]
Thanks for the issue report.  I'll try and get to this, and the other issues, this week.

**Comment by codella** [comment]
@chriswailes this should fix the issue https://github.com/chriswailes/RLTK/issues/39.

Would be nice to have this tested, QAd and merged asap, so we can rely on a more reliable `line_offset` :)

**Comment by chriswailes** [comment]
I merged the pull request, but it didn't seem to be related to this issue.  I was unable to reproduce the initial problem.  Here is the code I was using:

```Ruby
require 'rltk'

class TestLexer < RLTK::Lexer
     rule(/\s/)
     rule(/a/) { :A }
end

begin
     TestLexer.lex('   aaab')
rescue RLTK::LexingError => e
     puts e.message
     puts "Line number: #{e.line_number}"
     puts "Line offset: #{e.line_offset}"
end
```

This code correctly reports the offending character's offset as 6.

Output:

```
Unable to match string with any of the given rules: b
Line number: 1
Line offset: 6
```

**Comment by codella** [comment]
Sorry, I reported a very bad example - got confused myself :/ I'll take another chance to show you that the problem was there and now it's gone. Take the following code (inspired by yours):
```ruby
require 'rltk'

class TestLexer < RLTK::Lexer
     rule(/a/) { :A }
     rule(/[^ab]+/m) { :OTHER }
end

def lex(input)
  puts ">> Parsing #{input.inspect}..."
  TestLexer.lex(input)
rescue RLTK::LexingError => e
  puts e.message
  puts "Line number: #{e.line_number}"
  puts "Line offset: #{e.line_offset}"
end

lex("   \n\naaab")
puts "-" * 20
lex("   \n\n        aaab")
```

#### Output with RLTK 3.0.0
The output we get shows a wrong `line_offset` (3)...

```
>> Parsing "   \n\naaab"...
Unable to match string with any of the given rules: b
Line number: 3
Line offset: 3
--------------------
>> Parsing "   \n\n        aaab"...
Unable to match string with any of the given rules: b
Line number: 3
Line offset: 3
```

#### Output with RLTK 3.0.1
The output we get has a correct `line_offset` (11)...
```
>> Parsing "   \n\naaab"...
Unable to match string with any of the given rules: b
Line number: 3
Line offset: 3
--------------------
>> Parsing "   \n\n        aaab"...
Unable to match string with any of the given rules: b
Line number: 3
Line offset: 11
```

**Comment by codella** [comment]
@chriswailes ^^^^ :^)

**Comment by chriswailes** [comment]
I was definitely convinced that your patch fixed *a* problem; I just wanted to make sure it fixed *this* problem as well :-)
