### ISSUE TITLE
LLVM

### ISSUE THREAD

**Issue by amedeiros** [chriswailes/RLTK#53]
RLTK targets an older version of the LLVM (3.4). Is there any future plans of upgrading to support newer versions of the LLVM?

**Comment by chriswailes** [comment]
Yes, there is but I unfortunately don't have a timeframe for it.  The simplest answer is "I'll update it when the project I'm working on requires it" which I'm afraid isn't very helpful to other people.

However, if I know that people are interested in using an updated version of RLTK I'm more likely to work on it.  In the coming months I may have an opportunity to spend some time working on this project.  I'll try and make some announcement if that ends up being the case.

**Comment by amedeiros** [comment]
@chriswailes Ok thank you!
