### ISSUE TITLE
undefined method `subclass_of?'

### ISSUE THREAD

**Issue by ncallaway** [chriswailes/RLTK#54]
**Affected Versions**
Affects version `3.0.0` and version `3.0.1`. Does not affect version `2.2.1` or prior.

**Behavior**
In the more recent versions of the application when attempting to use a trivial parser we get a NoMethodError.

```
ast = TaskGrammar::TaskParser::parse(TaskGrammar::TaskLexer::lex(" "))
#=> NoMethodError (undefined method `subclass_of?' for TaskGrammar::TaskCompletion:Class)
```

When running this with `2.2.1` of the gem, this completes successfully.

```
ast = TaskGrammar::TaskParser::parse(TaskGrammar::TaskLexer::lex(" "))
=> #<TaskGrammar::TaskAst:0x000055d585cb2e00 @notes={}, @parent=nil, @c=#<TaskGrammar::TaskCompletion:0x000055d585cb34e0 @notes={}, @parent=#<TaskGrammar::TaskAst:0x000055d585cb2e00 ...>, @prefix="a", @infix="b">>
```

**Investigation**
It appears that the ast.rb file moved the `subclass_of?` definition to the `rltk/util/monkeys` file in commit `4565d5c` (https://github.com/chriswailes/RLTK/commit/4565d5c8bdcd4add579c16d818dec108dd565cdf).

In version 2.2.1 the util folder exists and contains the `monkeys.rb` file that defines `subclass_of?` (https://github.com/chriswailes/RLTK/tree/v2.2.1/lib/rltk). In version `3.0.0` the utils folder has been deleted (https://github.com/chriswailes/RLTK/tree/v3.0.0/lib/rltk), but no replacement method of `subclass_of?` appears to be defined.

**Comment by CBernsCode** [comment]
Thank you!
